### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by MrRabbit2MissCat** [Yzichen/mmLaneDet#11]
个人数据集，图片尺寸不一致 1920 *1080  1920*540 等，是否可以进行训练呢

**Comment by Yzichen** [comment]
The easiest way to do this is to first resize the image to the same size and align the corresponding annotations as well.

**Comment by MrRabbit2MissCat** [comment]
Thanks

**Comment by niann-git** [comment]
Hello, how exactly should I make my own dataset in dlrail format and train it? Why is it that training with my own dataset produces the following error:
File“/home/hty/prjs/DALNet/projects/mmlane_plugin/models/dense_heads/dalnet_head.py”, line 739, in forward
    cur_lanes_preds = torch.cat(cur_lanes_preds, dim=0) # (N_pos, 2+S)
NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat. This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

**Comment by niann-git** [comment]
Hello, how exactly should I make my own dataset in dlrail format and train it? Why is it that training with my own dataset produces the following error:
File“/projects/mmlane_plugin/models/dense_heads/dalnet_head.py”, line 739, in forward
cur_lanes_preds = torch.cat(cur_lanes_preds, dim=0) # (N_pos, 2+S)
NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat. This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].
