### ISSUE TITLE
Model download failure

### ISSUE THREAD

**Issue by MrRabbit2MissCat** [Yzichen/mmLaneDet#3]
google connection can not download, can provide Baidu web disk or Quark web disk, etc

**Comment by Yzichen** [comment]
It will take a while, maybe this weekend.

**Comment by MrRabbit2MissCat** [comment]
Thanks !!!

**Comment by cyn-liu** [comment]
@Yzichen 
Hello, I still can't download model.
permission problem:
![image](https://github.com/Yzichen/mmLaneDet/assets/104069308/ea98c336-43ee-4a7b-83ac-1bc5310acb4b)
I clicked on button `申请权限`, but still no response.
