### ISSUE TITLE
unable to download model weights file

### ISSUE THREAD

**Issue by cyn-liu** [Yzichen/mmLaneDet#5]
Hello @Yzichen :
Thanks for your open source, I still can't download model, and find permission problem:

![image](https://github.com/Yzichen/mmLaneDet/assets/104069308/f3cb26ed-19b0-481e-ba3e-d07b6c9a7a93)

I clicked on button `申请权限`, but still no response.

**Comment by Yzichen** [comment]
I'm very sorry. I have now changed the permissions and you can try the download again.

**Comment by cyn-liu** [comment]
Thank you very much!!!
