### ISSUE TITLE
Lane line detection distant bend does not fit

### ISSUE THREAD

**Issue by MrRabbit2MissCat** [Yzichen/mmLaneDet#6]
[https://github.com/MrRabbit2MissCat/data/blob/main/demo.jpg](url)
How do I adjust the parameters in this case? My own tusimple data set picture size is 1920*1080 h_samples=[320,1080]

**Comment by Yzichen** [comment]
I can't see the picture.

**Comment by MrRabbit2MissCat** [comment]
Open the browser connection, and I think you'll see it，or try it https://www.cnblogs.com/yunhgu/gallery/image/467112.html

**Comment by Yzichen** [comment]
It's a network performance issue and has nothing to do with tuning parameters.

**Comment by MrRabbit2MissCat** [comment]
OK, Thanks very much !!!
