### ISSUE TITLE
add new dataset and how to set parameters

### ISSUE THREAD

**Issue by cyn-liu** [Yzichen/mmLaneDet#7]
Hello @Yzichen 
In this project, I add the new open source lane detect dataset (OpenLane-v1), but I have some question would like to ask you:
for new dataset (OpenLane), how to set `FixedCrop` params `crop=(0, y_start, img_w, img_h)`? my img_w=1920 img_h=1280, I don't know how to set y_start.

In addition, In `./mmlane/dataset/xx_dataset.py`, how to set params `h_samples`?  `h_samples=list(range(y_start, img_h, y_step))`, so how to set `y_start` and `y_step`?

If you could give me some idea, I would be very grateful.
Thanks.

**Comment by Yzichen** [comment]
1. I think y_start just needs to make sure that it's truncating an irrelevant region, such as the sky.
2. The y_start in h_samples is just the same as FixedCrop's. For y_step, it affects the number and location of sampling points of predicting lanes. I usually simply set it to 10. However, you need to make sure that your eval process has no dependency on the sampling location of the predicted lanes.

**Comment by Yzichen** [comment]
By the way, I just read your FastBEV a couple days ago. pretty coincidental, haha.
